databases:
  - name: budget-app
    databaseName: budget_app_production
    user: teejay

services:
  - type: web
    name: teejay
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: teejay
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false